# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1da01def23048af38c6170985ffc8e145edb72b2727c3c17a6960880c5fdd694dbba5aa447ff4c56a0032cde50d11e2fe2ac1a1f371a39f5b3e1edb7661fd56b

test:
  secret_key_base: 793e0d2326eaa25c8f4c6e20da45d420388b46c4fc04bec8086066154ca5c5dfcc27468e1a10fc94ab023f0d6b272031faef9cc94880c41cadf8253d008512ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
